# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Steps toDo:
# 
# Trigger-Events
# (o) on new tags
# Required Build-Tooling
# (x/o) Visual Studio 2019(x) with C++ packages installed
# (o) Visual Studio 2015(x) with C++ packages installed (possible to have multipe versions?)
# (o) Visual Studio 2015(x) with C++ packages installed (possible to have multipe versions?)
# (x/0) New enough CMake
# (o) NASM compiler
# (o) Golang compiler
# (o) Apply fixes
# (o) Build Test-Package
# (o) Build Release-Package
# (o) Update Documentation

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- script: |
    choco install nasm -y
  displayName: 'Install dependencies'

- script: |
    echo '##vso[task.prependpath]C:\Program Files\NASM'
    echo "$PATH"'
    cmake --version
    python --version
    nasm --version
  displayName: 'Show information build tools'

- script: |
    git clone --depth=1 -b v1.47.0 https://github.com/grpc/grpc
    cd grpc
    git submodule update --init --depth=1
  displayName: 'Checkout Sources'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
