- name: Azure Pipelines Action
  uses: Azure/pipelines@v1.2
  with:
    # Fullyqualified URL to the Azure DevOps organization along with project name(eg, https://dev.azure.com/organization/project-name or https://server.example.com:8080/tfs/DefaultCollection/project-name)
    azure-devops-project-url: 
    # Name of the Azure Pipline to be triggered
    azure-pipeline-name: 
    # Set/Overwrite pipeline variables
    azure-pipeline-variables: # optional
    # Paste personal access token of the user as value of secret variable:AZURE_DEVOPS_TOKEN
    azure-devops-token: 
